# Generated by Django 4.2.6 on 2023-10-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfCrimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_crime', models.CharField(default=None, max_length=50)),
                ('bg_color', models.CharField(default=None, max_length=50)),
                ('desc', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
