# Generated by Django 4.2.6 on 2023-10-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_authuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
