# Generated by Django 4.2.6 on 2023-10-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_authuser_is_active_authuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='is_active',
        ),
    ]
