# Generated by Django 4.2.6 on 2023-10-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_authuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('datecreated', models.DateField()),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
