# Generated by Django 4.2.6 on 2023-10-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_customuser_datecreated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
